### ISSUE TITLE
Could not find static manifest

### ISSUE THREAD

**Issue by MeterSoft** [schnittchen/onartsipac#30]
Got error when deploy
New Error: #1 Could not find static manifest at "/home/property/three_taps/backpage_scraper/release/lib/backpage_scraper-0.0.1/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".

It is possible do mix phx.digest from deploy?

**Comment by schnittchen** [comment]
Did you add a custom task to build assets like here https://hexdocs.pm/carafe/customtasks.html#building-assets-into-the-release-with-brunch ? If yes, did it run? You can pass `--trace` to capistrano to see which tasks exactly are run.

**Comment by MeterSoft** [comment]
It is my deploy file
`task "deploy" => [
  "buildhost:generate_release",
  "buildhost:archive:download",
  "node:archive:upload_and_unpack",
  "node:full_restart"
]

task :copy_configs do
 
end

task "build:assets" do
  on roles(:build) do |host|

    within build_path do
      with mix_env: mix_env do
        execute :mix, "phx.digest"
      end
    end
  end
end

after 'buildhost:prepare_build_path', :copy_configs`

when i should call asset task?

**Comment by MeterSoft** [comment]
looks like this works
`after 'buildhost:compile', "build:assets"`

**Comment by schnittchen** [comment]
I need to make this clearer in the documentation.
