### ISSUE TITLE
deploy without build server

### ISSUE THREAD

**Issue by MeterSoft** [schnittchen/onartsipac#32]
He, Is it possible to deploy without build server. I don not wont download and upload project. Can i build and unpack it on one server?

**Comment by schnittchen** [comment]
Hi,

I thought I have an issue around this, but it seems I have not.

The proper way would be to have an API for varying storage providers. Since there seems to be a new deployment tool written in Elixir proper at the horizon, I probably will not put significant time into this.


Meanwhile, this might do the trick:

```
task "buildhost:archive:make_available" => "buildhost:archive_path" do
  on build_host do |host|
    execute :mkdir, "-p", "~/latest_release/"
    execute :cp, fetch(:buildhost_archive_path), "~/latest_release/archive.tar.gz"
  end 
end

task "node:archive:obtain" do
  on app_hosts do |host|
    execute :mkdir, "-p", app_path
    execute :cp, "~/latest_release/archive.tar.gz", app_path.join("archive.tar.gz")
  end 
end
```

Then your deploy task should no longer depend on `buildhost:archive:download` and `node:archive:upload_and_unpack` but on `buildhost:archive:make_available`, `node:archive:obtain` and `node:archive:unpack`, in order.

**Comment by MeterSoft** [comment]
When i create custom task with same name as carafe task it should override this? Because now not.

**Comment by MeterSoft** [comment]
this haw it works for me

```
task "deploy" => [
  "buildhost:custom_generate_release",
  "node:archive:custom_upload_and_unpack",
  "node:full_restart"
]

task "node:archive:custom_upload_and_unpack" => "buildhost:archive_path" do
  buildhost_archive_path = fetch(:buildhost_archive_path)

  Rake::Task["node:archive:custom_upload"].invoke(buildhost_archive_path)
  Rake::Task["node:archive:unpack"].invoke
end

desc "Generate release on the build host"
task "buildhost:custom_generate_release" => [
  "buildhost:prepare_build_path",
  "buildhost:copy_configs",
  "buildhost:custom_compile",
  "buildhost:mix:release"
]

desc "Compile entire project at the build path on the build host"
task "buildhost:custom_compile" => [
  "buildhost:mix:deps.get",
  "buildhost:mix:compile",
  "buildhost:mix:assets"
]
task "node:archive:custom_upload", [:archive_path] => "buildhost:archive_path" do |t, args|
  on app_hosts do |host|
    execute :mkdir, "-p", app_path
    execute :cp, args[:archive_path], app_path.join("archive.tar.gz")
  end
end
```

**Comment by schnittchen** [comment]
Hi @MeterSoft, please use triple backticks (```) around multi-line code snippets (see https://github.github.com/gfm/#fenced-code-blocks). Thank you!

**Comment by schnittchen** [comment]
Sorry for the delay, I only just saw you edited the code.

Looks good, thank you for sharing! Glad it works for you :)
